

<TextInput_Standard>:

    #background_normal: ""
    #background_color: (1, 1, 1, 1)


    canvas.before:
        Color:
            rgba: (1, 1, 1, 1)
        RoundedRectangle:
            size: self.size
            pos: {.5, .6}
            radius: [10]

<RoundedTextInput>:
    id: text_input
    size_hint: (1, 1)
    cursor_color: (0,0,0,1)
    hint_text: "Password"
    hint_text_color: (.02, .02, .01, .5)
    #foreground_color: [1,1,1,1]
    background_color: [0,0,0,0]
    background_image: ""
    background_normal: ""
    background_active: ""


    multiline: False


    #canvas.before:
     #   Color:
       #     rgba: (0, 0, 0, 1)

    canvas.after:
        Color:
            rgba: [1, 1, 1, 0] if self.focused else (.8,.8,.8,0)
        RoundedRectangle:
            size: self.size
            pos: self.pos
            radius: [10]








