


<TextInput_Standard>:
    id: text_input
    size_hint: (1, 1)
    cursor_color: (0,0,0,1)
    hint_text: "Password"
    hint_text_color: (.8, .8, .8, 1)
    #foreground_color: [1,1,1,1]
    #background_color: [0,0,0,0]
    #background_image: "resources/img.png"
    background_normal: "resources/text_input_figma_test.png"
    background_active: "resources/text_input_from_figma_gold.png"
    #border: (4, 4, 4, 4)


    multiline: False

