
<Pop_LanguageMenu>:

    title: "Choose Language"
    title_size: 30

    title_align: "center"
    size_hint: (.588, .7)
    pos_hint: {"x":.4, "top": .95}
    title_color: (0, 0, 0, 1)
    separator_color: (0, 0, 0, 1)
    separator_height: "1dp"
    padding: 0
    background: "resources/images/burger_menu_BACKGROUND.png"

    RelativeLayout:
        id: main_frame
        background_color: (1, 1, 1, 1)

